### ISSUE TITLE
Confusion between latent variable and LSTM hidden states in the code

### ISSUE THREAD

**Issue by ghazi-f** [ruizheliUOA/HR-VAE#2]
Hello Sir,

From ```HR-VAE.py``` line 151, it seems that you're returning the zipped LSTM hidden states as a first output. You use it afterwards (line 309) as ```z```. The way I understand it, this is not correct as you're supposed to sample z using the ```mu``` and ```logvar``` you produced with the linear layers in your encoder. 
Is there something I'm missing here ?

**Comment by ruizheliUOA** [comment]
> Hello Sir,
> 
> From `HR-VAE.py` line 151, it seems that you're returning the zipped LSTM hidden states as a first output. You use it afterwards (line 309) as `z`. The way I understand it, this is not correct as you're supposed to sample z using the `mu` and `logvar` you produced with the linear layers in your encoder.
> Is there something I'm missing here ?

Hi, if you look at line 140, `h` actually represents the sampled `z`. (sorry about using an unsuitable variable name to represent sampled `z` here).

**Comment by ghazi-f** [comment]
Ah, right ! Sorry I thought ```h``` was returned as obtained in line 136.
Thank you for the explanation.
